id: PB8299E68
initial_creation_type: ocr
source_metadata:
  volumes:
    9a6393befc4d40fb9cf8139a9e78e0b0:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: མདོ་ཀུན་ལས་བཏུས་པའི་དོན་བསྡུས་པ།
      total_pages: 1902
      volume_number: 64
